name: CI

on:
  push:
    baranches:
      - "develop"

  jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [15.x]

      steps:
        - uses: actions/checkout@v1
        - run: yarn install
        - run: yarn build