#name: CI
#
#on:
#  push:
#    baranches:
#     - "develop"
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [15.x]
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name:  Set up Node.js ${{ matrix.node-version }}
#        uses: actions/checkout@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#
#      - name: Install dependencies
#        run: yarn install
#
#      - name: Build
#        run: yarn build
#
#      - name: Deploy
#        run: |
#          git config --global user.name $user_name
#          git config --global user.email $user_email
#          git remote set-url origin https://${github_token}@github.com/${repository}
#          npm run deploy
#        env:
#          user_name: 'github-actions[bot]'
#          user_email: 'github-actions[bot]@users.noreply.github.com'
#          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
#          repository: ${{ github.repository }}

name: agroup-user-front CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use agroup-user-front ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          ls -la
          npm install
          ls -la
          npm run build
          docker build -t 'ci-1' .
          docker stop 'test-ci' || true
          docker rm 'test-ci' --force || true
          docker run --rm -d -p '7575:5000' --name 'test-ci' 'ci-1'